frase='Curso em Video Python'
print(frase)
print(len(frase))
print(frase[9:21])
print(frase.count('o'),'count')
print(frase.find('deo'),'find')
print(frase.find('Android'),'find')
print('Curso' in frase,'in')
print(frase.replace('Python','Android'),'replace')
print(frase.upper(),'upper')
print(frase.lower(),'lower')
print(frase.capitalize(),'capitalize')
print(frase.title(),'title')
print(frase.strip(),'strip')
print(frase.rstrip(),'rstrip')
print(frase.lstrip(),'lstrip')
dividido = frase.split()
print(dividido[0],'split')
print(dividido[3][1],'split')
frase=frase.replace(' ','')
print('-'.join(frase),'join')
print("""While The Python Language Reference describes the exact syntax and semantics of the Python language,
this library reference manual describes the standard library that is distributed with Python. It also describes 
some of the optional components that are commonly included in Python distributions.""")
