a=input('digite algo: ')
print('O tipo primitivo desse valor é ',type(a))
print('So tem espaços',a.isspace())
print('é um numero ',a.isnumeric())
print('é um alfabetico ',a.isalpha())
print('é um alganumerico ',a.isalnum())
print('Esta em maiusculas ',a.isupper())
print('Esta em minusculas ',a.islower())
print('Esta captalizada ',a.istitle())
